### ISSUE TITLE
Tests are failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by jkcailteux** [darcius/rocketpool#10]
I'm on Ubuntu 16.04 on a VM (virtual box) getting this error.

![capture](https://user-images.githubusercontent.com/2236167/34511391-09a22248-f010-11e7-93a3-8ec20dca8b14.PNG)

**Comment by darcius** [comment]
Hey Jeff, just gave it a run and everything is passing for me. Looks like it could be an issue with your node version since it's throwing on the promise which requires Node 8 or better. Can you type `node -v` into the VM console and check? If it's less than 8, I'd recommend upgrading and trying again.

If it is greater than 8, type in `truffle version` into the console and let me know what it says.

**Comment by jkcailteux** [comment]
That was it! I think a fresh install of ubuntu has node 6.0 as the default. Upgraded to 9 and everything ran smoothly.

**Comment by darcius** [comment]
Awesome Jeff, glad you got it running mate :)
